language: node_js
cache: npm
node_js:
  - '6'
  - '8'
  - '10'
script:
  - npm install -g codecov
  - TZ=America/Vancouver npm run test-ci
  - TZ=America/Los_Angeles npm run test-ci
  - TZ=Africa/Nairobi npm run test-ci
  - TZ=Asia/Tokyo npm run test-ci
after_success:
  - codecov
sudo: false
